-- Migration script to fix UUID columns from bytea to uuid type
-- 
-- PROBLEM: PostgreSQL is storing UUIDs as bytea instead of uuid type,
-- causing errors like "function lower(bytea) does not exist"
--
-- SOLUTION: The easiest fix is to drop and recreate the database
-- since Hibernate will now create columns with the correct uuid type
-- (we've updated all entity classes with columnDefinition = "uuid")
--
-- RECOMMENDED APPROACH (if you can re-seed data):
-- 1. Stop your Spring Boot application
-- 2. Connect to PostgreSQL: psql -U postgres
-- 3. Run: DROP DATABASE scotia_budget;
-- 4. Run: CREATE DATABASE scotia_budget;
-- 5. Restart your Spring Boot application
-- 6. Hibernate will recreate all tables with correct uuid types
--
-- ALTERNATIVE (if you need to preserve data):
-- This is more complex and requires exporting/importing data.
-- Consider using pg_dump/pg_restore or a data migration tool.
